### PR TITLE
Add support for --connect-to to override host and port

### LINKED ISSUE #115: Provide option similar to curl's `--connect-to`
This is probably a rare use case (but it's ours!).

`curl` provides a `connect-to` option to override DNS resolution and always connect directly to an IP address for a given hostname+port.

Since `oha` uses hyper, and `hyper` allows passing a `Resolver`, it seems this would be reasonably easy to implement. I can try and give it a shot if you'd accept a PR for that in oha.

Let me know what you think!

### PR DESCRIPTION
**Pull request by fasterthanlime**
This closes #115.

The option has help text provided by structopt and behaves like curl's `--connect-to`.

### CODE REVIEW

**Comment by hatoo** [comment]
I believe `connect_to` should be applied also in redirection.

https://github.com/hatoo/oha/blob/10b1dc0103c11e8144f3a61cbb481092d24a2062/src/client.rs#L326-L328

I think it's good to extend `DNS` struct to have `Vec<ConnectToEntry>` and make `lookup_ip` also returns port and call just `lookup_ip` from `work` and `redirect` to look up id and get port.

**Comment by hatoo** [comment]
if you don't mind, I recommend making some tests on `tests/tests.rs`.

**Comment by hatoo** [comment]
Could you make some updates to CHANGELOG.md's `Unreleased` section?  it's a new feature.

**Comment by hatoo** [comment]
Could you follow `clippy`'?
https://github.com/hatoo/oha/pull/116/checks?check_run_id=1385094622

I guess it's just convert ":" to ':'.

**Comment by fasterthanlime** [comment]
Fixed a couple things, going to work on tests and changelog next. Thanks for the feedback so far!

**Comment by fasterthanlime** [comment]
I think that's all of it! There's a test without redirects, and a test with redirects.

I also fixed a clippy for a test (that wasn't mine), and a typo in the changelog for 0.4.1.

Also some performance work (`Arc` to avoid cloning so much).

**Comment by hatoo** [comment]
Looks great!
Thank you very much!

**Pull request merged**
